using System;
using System.Collections.Generic;
using System.Text;

namespace SoundDevices.IO.WinMM.Internal
{
    internal enum MMManufacturerID : ushort
    {
        MM_MICROSOFT = 1,           /* Microsoft Corporation */
        MM_CREATIVE = 2,           /* Creative Labs, Inc. */
        MM_MEDIAVISION = 3,           /* Media Vision, Inc. */
        MM_FUJITSU = 4,           /* Fujitsu Corp. */
        MM_PRAGMATRAX = 5,           /* PRAGMATRAX Software */
        MM_CYRIX = 6,           /* Cyrix Corporation */
        MM_PHILIPS_SPEECH_PROCESSING = 7,           /* Philips Speech Processing */
        MM_NETXL = 8,           /* NetXL, Inc. */
        MM_ZYXEL = 9,           /* ZyXEL Communications, Inc. */
        MM_BECUBED = 10,          /* BeCubed Software Inc. */
        MM_AARDVARK = 11,          /* Aardvark Computer Systems, Inc. */
        MM_BINTEC = 12,          /* Bin Tec Communications GmbH */
        MM_HEWLETT_PACKARD = 13,          /* Hewlett-Packard Company */
        MM_ACULAB = 14,          /* Aculab plc */
        MM_FAITH = 15,          /* Faith,Inc. */
        MM_MITEL = 16,          /* Mitel Corporation */
        MM_QUANTUM3D = 17,          /* Quantum3D, Inc. */
        MM_SNI = 18,          /* Siemens-Nixdorf */
        MM_EMU = 19,          /* E-mu Systems, Inc. */
        MM_ARTISOFT = 20,          /* Artisoft, Inc. */
        MM_TURTLE_BEACH = 21,          /* Turtle Beach, Inc. */
        MM_IBM = 22,          /* IBM Corporation */
        MM_VOCALTEC = 23,          /* Vocaltec Ltd. */
        MM_ROLAND = 24,          /* Roland */
        MM_DSP_SOLUTIONS = 25,          /* DSP Solutions, Inc. */
        MM_NEC = 26,          /* NEC */
        MM_ATI = 27,          /* ATI Technologies Inc. */
        MM_WANGLABS = 28,          /* Wang Laboratories, Inc. */
        MM_TANDY = 29,          /* Tandy Corporation */
        MM_VOYETRA = 30,          /* Voyetra */
        MM_ANTEX = 31,          /* Antex Electronics Corporation */
        MM_ICL_PS = 32,          /* ICL Personal Systems */
        MM_INTEL = 33,          /* Intel Corporation */
        MM_GRAVIS = 34,          /* Advanced Gravis */
        MM_VAL = 35,          /* Video Associates Labs, Inc. */
        MM_INTERACTIVE = 36,          /* InterActive Inc. */
        MM_YAMAHA = 37,          /* Yamaha Corporation of America */
        MM_EVEREX = 38,          /* Everex Systems, Inc. */
        MM_ECHO = 39,          /* Echo Speech Corporation */
        MM_SIERRA = 40,          /* Sierra Semiconductor Corp */
        MM_CAT = 41,          /* Computer Aided Technologies */
        MM_APPS = 42,          /* APPS Software International */
        MM_DSP_GROUP = 43,          /* DSP Group, Inc. */
        MM_MELABS = 44,          /* microEngineering Labs */
        MM_COMPUTER_FRIENDS = 45,          /* Computer Friends, Inc. */
        MM_ESS = 46,          /* ESS Technology */
        MM_AUDIOFILE = 47,          /* Audio, Inc. */
        MM_MOTOROLA = 48,          /* Motorola, Inc. */
        MM_CANOPUS = 49,          /* Canopus, co., Ltd. */
        MM_EPSON = 50,          /* Seiko Epson Corporation */
        MM_TRUEVISION = 51,          /* Truevision */
        MM_AZTECH = 52,          /* Aztech Labs, Inc. */
        MM_VIDEOLOGIC = 53,          /* Videologic */
        MM_SCALACS = 54,          /* SCALACS */
        MM_KORG = 55,          /* Korg Inc. */
        MM_APT = 56,          /* Audio Processing Technology */
        MM_ICS = 57,          /* Integrated Circuit Systems, Inc. */
        MM_ITERATEDSYS = 58,          /* Iterated Systems, Inc. */
        MM_METHEUS = 59,          /* Metheus */
        MM_LOGITECH = 60,          /* Logitech, Inc. */
        MM_WINNOV = 61,          /* Winnov, Inc. */
        MM_NCR = 62,          /* NCR Corporation */
        MM_EXAN = 63,          /* EXAN */
        MM_AST = 64,          /* AST Research Inc. */
        MM_WILLOWPOND = 65,          /* Willow Pond Corporation */
        MM_SONICFOUNDRY = 66,          /* Sonic Foundry */
        MM_VITEC = 67,          /* Vitec Multimedia */
        MM_MOSCOM = 68,          /* MOSCOM Corporation */
        MM_SILICONSOFT = 69,          /* Silicon Soft, Inc. */
        MM_TERRATEC = 70,          /* TerraTec Electronic GmbH */
        MM_MEDIASONIC = 71,          /* MediaSonic Ltd. */
        MM_SANYO = 72,          /* SANYO Electric Co., Ltd. */
        MM_SUPERMAC = 73,          /* Supermac */
        MM_AUDIOPT = 74,          /* Audio Processing Technology */
        MM_NOGATECH = 75,          /* NOGATECH Ltd. */
        MM_SPEECHCOMP = 76,          /* Speech Compression */
        MM_AHEAD = 77,          /* Ahead, Inc. */
        MM_DOLBY = 78,          /* Dolby Laboratories */
        MM_OKI = 79,          /* OKI */
        MM_AURAVISION = 80,          /* AuraVision Corporation */
        MM_OLIVETTI = 81,          /* Ing C. Olivetti & C., S.p.A. */
        MM_IOMAGIC = 82,          /* I/O Magic Corporation */
        MM_MATSUSHITA = 83,          /* Matsushita Electric Industrial Co., Ltd. */
        MM_CONTROLRES = 84,          /* Control Resources Limited */
        MM_XEBEC = 85,          /* Xebec Multimedia Solutions Limited */
        MM_NEWMEDIA = 86,          /* New Media Corporation */
        MM_NMS = 87,          /* Natural MicroSystems */
        MM_LYRRUS = 88,          /* Lyrrus Inc. */
        MM_COMPUSIC = 89,          /* Compusic */
        MM_OPTI = 90,          /* OPTi Computers Inc. */
        MM_ADLACC = 91,          /* Adlib Accessories Inc. */
        MM_COMPAQ = 92,          /* Compaq Computer Corp. */
        MM_DIALOGIC = 93,          /* Dialogic Corporation */
        MM_INSOFT = 94,          /* InSoft, Inc. */
        MM_MPTUS = 95,          /* M.P. Technologies, Inc. */
        MM_WEITEK = 96,          /* Weitek */
        MM_LERNOUT_AND_HAUSPIE = 97,          /* Lernout & Hauspie */
        MM_QCIAR = 98,          /* Quanta Computer Inc. */
        MM_APPLE = 99,          /* Apple Computer, Inc. */
        MM_DIGITAL = 100,         /* Digital Equipment Corporation */
        MM_MOTU = 101,         /* Mark of the Unicorn */
        MM_WORKBIT = 102,         /* Workbit Corporation */
        MM_OSITECH = 103,         /* Ositech Communications Inc. */
        MM_MIRO = 104,         /* miro Computer Products AG */
        MM_CIRRUSLOGIC = 105,         /* Cirrus Logic */
        MM_ISOLUTION = 106,         /* ISOLUTION  B.V. */
        MM_HORIZONS = 107,         /* Horizons Technology, Inc. */
        MM_CONCEPTS = 108,         /* Computer Concepts Ltd. */
        MM_VTG = 109,         /* Voice Technologies Group, Inc. */
        MM_RADIUS = 110,         /* Radius */
        MM_ROCKWELL = 111,         /* Rockwell International */
        MM_XYZ = 112,         /* Co. XYZ for testing */
        MM_OPCODE = 113,         /* Opcode Systems */
        MM_VOXWARE = 114,         /* Voxware Inc. */
        MM_NORTHERN_TELECOM = 115,         /* Northern Telecom Limited */
        MM_APICOM = 116,         /* APICOM */
        MM_GRANDE = 117,         /* Grande Software */
        MM_ADDX = 118,         /* ADDX */
        MM_WILDCAT = 119,         /* Wildcat Canyon Software */
        MM_RHETOREX = 120,         /* Rhetorex Inc. */
        MM_BROOKTREE = 121,         /* Brooktree Corporation */
        MM_ENSONIQ = 125,         /* ENSONIQ Corporation */
        MM_FAST = 126,         /* FAST Multimedia AG */
        MM_NVIDIA = 127,         /* NVidia Corporation */
        MM_OKSORI = 128,         /* OKSORI Co., Ltd. */
        MM_DIACOUSTICS = 129,         /* DiAcoustics, Inc. */
        MM_GULBRANSEN = 130,         /* Gulbransen, Inc. */
        MM_KAY_ELEMETRICS = 131,         /* Kay Elemetrics, Inc. */
        MM_CRYSTAL = 132,         /* Crystal Semiconductor Corporation */
        MM_SPLASH_STUDIOS = 133,         /* Splash Studios */
        MM_QUARTERDECK = 134,         /* Quarterdeck Corporation */
        MM_TDK = 135,         /* TDK Corporation */
        MM_DIGITAL_AUDIO_LABS = 136,         /* Digital Audio Labs, Inc. */
        MM_SEERSYS = 137,         /* Seer Systems, Inc. */
        MM_PICTURETEL = 138,         /* PictureTel Corporation */
        MM_ATT_MICROELECTRONICS = 139,         /* AT&T Microelectronics */
        MM_OSPREY = 140,         /* Osprey Technologies, Inc. */
        MM_MEDIATRIX = 141,         /* Mediatrix Peripherals */
        MM_SOUNDESIGNS = 142,         /* SounDesignS M.C.S. Ltd. */
        MM_ALDIGITAL = 143,         /* A.L. Digital Ltd. */
        MM_SPECTRUM_SIGNAL_PROCESSING = 144,         /* Spectrum Signal Processing, Inc. */
        MM_ECS = 145,         /* Electronic Courseware Systems, Inc. */
        MM_AMD = 146,         /* AMD */
        MM_COREDYNAMICS = 147,         /* Core Dynamics */
        MM_CANAM = 148,         /* CANAM Computers */
        MM_SOFTSOUND = 149,         /* Softsound, Ltd. */
        MM_NORRIS = 150,         /* Norris Communications, Inc. */
        MM_DDD = 151,         /* Danka Data Devices */
        MM_EUPHONICS = 152,         /* EuPhonics */
        MM_PRECEPT = 153,         /* Precept Software, Inc. */
        MM_CRYSTAL_NET = 154,         /* Crystal Net Corporation */
        MM_CHROMATIC = 155,         /* Chromatic Research, Inc. */
        MM_VOICEINFO = 156,         /* Voice Information Systems, Inc. */
        MM_VIENNASYS = 157,         /* Vienna Systems */
        MM_CONNECTIX = 158,         /* Connectix Corporation */
        MM_GADGETLABS = 159,         /* Gadget Labs LLC */
        MM_FRONTIER = 160,         /* Frontier Design Group LLC */
        MM_VIONA = 161,         /* Viona Development GmbH */
        MM_CASIO = 162,         /* Casio Computer Co., LTD */
        MM_DIAMONDMM = 163,         /* Diamond Multimedia */
        MM_S3 = 164,         /* S3 */
        MM_DVISION = 165,         /* D-Vision Systems, Inc. */
        MM_NETSCAPE = 166,         /* Netscape Communications */
        MM_SOUNDSPACE = 167,         /* Soundspace Audio */
        MM_VANKOEVERING = 168,         /* VanKoevering Company */
        MM_QTEAM = 169,         /* Q-Team */
        MM_ZEFIRO = 170,         /* Zefiro Acoustics */
        MM_STUDER = 171,         /* Studer Professional Audio AG */
        MM_FRAUNHOFER_IIS = 172,         /* Fraunhofer IIS */
        MM_QUICKNET = 173,         /* Quicknet Technologies */
        MM_ALARIS = 174,         /* Alaris, Inc. */
        MM_SICRESOURCE = 175,         /* SIC Resource Inc. */
        MM_NEOMAGIC = 176,         /* NeoMagic Corporation */
        MM_MERGING_TECHNOLOGIES = 177,         /* Merging Technologies S.A. */
        MM_XIRLINK = 178,         /* Xirlink, Inc. */
        MM_COLORGRAPH = 179,         /* Colorgraph (UK) Ltd */
        MM_OTI = 180,         /* Oak Technology, Inc. */
        MM_AUREAL = 181,         /* Aureal Semiconductor */
        MM_VIVO = 182,         /* Vivo Software */
        MM_SHARP = 183,         /* Sharp */
        MM_LUCENT = 184,         /* Lucent Technologies */
        MM_ATT = 185,         /* AT&T Labs, Inc. */
        MM_SUNCOM = 186,         /* Sun Communications, Inc. */
        MM_SORVIS = 187,         /* Sorenson Vision */
        MM_INVISION = 188,         /* InVision Interactive */
        MM_BERKOM = 189,         /* Deutsche Telekom Berkom GmbH */
        MM_MARIAN = 190,         /* Marian GbR Leipzig */
        MM_DPSINC = 191,         /* Digital Processing Systems, Inc. */
        MM_BCB = 192,         /* BCB Holdings Inc. */
        MM_MOTIONPIXELS = 193,         /* Motion Pixels */
        MM_QDESIGN = 194,         /* QDesign Corporation */
        MM_NMP = 195,         /* Nokia Mobile Phones */
        MM_DATAFUSION = 196,         /* DataFusion Systems (Pty) (Ltd) */
        MM_DUCK = 197,         /* The Duck Corporation */
        MM_FTR = 198,         /* Future Technology Resources Pty Ltd */
        MM_BERCOS = 199,         /* BERCOS GmbH */
        MM_ONLIVE = 200,         /* OnLive! Technologies, Inc. */
        MM_SIEMENS_SBC = 201,         /* Siemens Business Communications Systems */
        MM_TERALOGIC = 202,         /* TeraLogic, Inc. */
        MM_PHONET = 203,         /* PhoNet Communications Ltd. */
        MM_WINBOND = 204,         /* Winbond Electronics Corp */
        MM_VIRTUALMUSIC = 205,         /* Virtual Music, Inc. */
        MM_ENET = 206,         /* e-Net, Inc. */
        MM_GUILLEMOT = 207,         /* Guillemot International */
        MM_EMAGIC = 208,         /* Emagic Soft- und Hardware GmbH */
        MM_MWM = 209,         /* MWM Acoustics LLC */
        MM_PACIFICRESEARCH = 210,         /* Pacific Research and Engineering Corporation */
        MM_SIPROLAB = 211,         /* Sipro Lab Telecom Inc. */
        MM_LYNX = 212,         /* Lynx Studio Technology, Inc. */
        MM_SPECTRUM_PRODUCTIONS = 213,         /* Spectrum Productions */
        MM_DICTAPHONE = 214,         /* Dictaphone Corporation */
        MM_QUALCOMM = 215,         /* QUALCOMM, Inc. */
        MM_RZS = 216,         /* Ring Zero Systems, Inc */
        MM_AUDIOSCIENCE = 217,         /* AudioScience Inc. */
        MM_PINNACLE = 218,         /* Pinnacle Systems, Inc. */
        MM_EES = 219,         /* EES Technik fuer Musik GmbH */
        MM_HAFTMANN = 220,         /* haftmann#software */
        MM_LUCID = 221,         /* Lucid Technology, Symetrix Inc. */
        MM_HEADSPACE = 222,         /* Headspace, Inc */
        MM_UNISYS = 223,         /* UNISYS CORPORATION */
        MM_LUMINOSITI = 224,         /* Luminositi, Inc. */
        MM_ACTIVEVOICE = 225,         /* ACTIVE VOICE CORPORATION */
        MM_DTS = 226,         /* Digital Theater Systems, Inc. */
        MM_DIGIGRAM = 227,         /* DIGIGRAM */
        MM_SOFTLAB_NSK = 228,         /* Softlab-Nsk */
        MM_FORTEMEDIA = 229,         /* ForteMedia, Inc */
        MM_SONORUS = 230,         /* Sonorus, Inc. */
        MM_ARRAY = 231,         /* Array Microsystems, Inc. */
        MM_DATARAN = 232,         /* Data Translation, Inc. */
        MM_I_LINK = 233,         /* I-link Worldwide */
        MM_SELSIUS_SYSTEMS = 234,         /* Selsius Systems Inc. */
        MM_ADMOS = 235,         /* AdMOS Technology, Inc. */
        MM_LEXICON = 236,         /* Lexicon Inc. */
        MM_SGI = 237,         /* Silicon Graphics Inc. */
        MM_IPI = 238,         /* Interactive Product Inc. */
        MM_ICE = 239,         /* IC Ensemble, Inc. */
        MM_VQST = 240,         /* ViewQuest Technologies Inc. */
        MM_ETEK = 241,         /* eTEK Labs Inc. */
        MM_CS = 242,         /* Consistent Software */
        MM_ALESIS = 243,         /* Alesis Studio Electronics */
        MM_INTERNET = 244,         /* INTERNET Corporation */
        MM_SONY = 245,         /* Sony Corporation */
        MM_HYPERACTIVE = 246,         /* Hyperactive Audio Systems, Inc. */
        MM_UHER_INFORMATIC = 247,         /* UHER informatic GmbH */
        MM_SYDEC_NV = 248,         /* Sydec NV */
        MM_FLEXION = 249,         /* Flexion Systems Ltd. */
        MM_VIA = 250,         /* Via Technologies, Inc. */
        MM_MICRONAS = 251,         /* Micronas Semiconductors, Inc. */
        MM_ANALOGDEVICES = 252,         /* Analog Devices, Inc. */
        MM_HP = 253,         /* Hewlett Packard Company */
        MM_MATROX_DIV = 254,         /* Matrox */
        MM_QUICKAUDIO = 255,         /* Quick Audio, GbR */
        MM_YOUCOM = 256,         /* You/Com Audiocommunicatie BV */
        MM_RICHMOND = 257,         /* Richmond Sound Design Ltd. */
        MM_IODD = 258,         /* I-O Data Device, Inc. */
        MM_ICCC = 259,         /* ICCC A/S */
        MM_3COM = 260,         /* 3COM Corporation */
        MM_MALDEN = 261,         /* Malden Electronics Ltd. */
        MM_3DFX = 262,         /* 3Dfx Interactive, Inc. */
        MM_MINDMAKER = 263,         /* Mindmaker, Inc. */
        MM_TELEKOL = 264,         /* Telekol Corp. */
        MM_ST_MICROELECTRONICS = 265,         /* ST Microelectronics */
        MM_ALGOVISION = 266,         /* Algo Vision Systems GmbH */
        MM_UNMAPPED = 0xffff,      /* extensible MID mapping */
    }
}
                               